In [2]:
# 1. What is the difference b/w list and numpy?
# 2. How do you create a user defined array?
# 3. Create an random array in range 100-200 and total
#    value will be 64 and you have to reshape it to all possible
#    factors?
# 4. Create an array of (5,5) in which all the values will be 7.
# 5. difference b/w view vs copy with example.
# 6. difference b/w linspace() and unique() with code of example
# 7. what is hstack() and vstack()? Create 4 array and connect it via hstack, vstack
# 8. Create an array in range 11-26. Now you have to reshape it 4*4 and
#    then you have to calculate total sum, row wise sum and column wise sum.

In [9]:
# 1. What is the difference b/w list and numpy?
'''
Numpy arrays and Python lists are both used to store collection of data. But they differ significantly
in their characterstics and use case:
1. Numpy is designed to store homogeneous(same type) data where list can take different type of data.
2. Numpy is faster than python list
3. Numpy consumes less memory than python list
4. Numpy provides much more mathematical function and operations to optimize
   the calculation than python list.
'''

'\nNumpy arrays and Python lists are both used to store collection of data. But they differ significantly\nin their characterstics and use case:\n1. Numpy is designed to store homogeneous(same type) data where list can take different type of data.\n2. Numpy is faster than python list\n3. Numpy consumes less memory than python list\n4. Numpy provides much more mathematical function and operations to optimize \n   the calculation than python list.\n'

In [10]:
# 2. How do you create a user defined array?
import numpy as np
l = []
for i in range(3):
  print('ENter Number:')
  n = int(input())
  l.append(n)
arr = np.array(l)
arr

ENter Number:
4
ENter Number:
5
ENter Number:
6


array([4, 5, 6])

In [20]:
# 3. Create an random array in range 100-200 and total
#    value will be 64 and you have to reshape it to all possible
#    factors?
arr1 = np.random.randint(100,200,64)
print(arr1)
# 64 :-
# 1x64 , 64x1
arr2 = arr1.reshape((64,1))
print(arr2)
# 2x32 , 32x2
arr3 = arr1.reshape((32,2))
print(arr3)
arr4 = arr1.reshape((2,32))
print(arr4)
# 4x16 , 16x4
arr5 = arr1.reshape((4,16))
print(arr5)
arr5 = arr1.reshape((16,4))
print(arr5)
# 8x8
arr6 = arr1.reshape((8,8))
print(arr6)

[151 194 143 149 114 102 172 198 138 187 164 106 139 119 196 110 119 100
 158 109 109 135 179 176 150 141 148 180 123 145 128 157 140 154 190 101
 146 116 129 197 167 151 187 137 188 144 176 164 156 101 147 182 148 146
 167 112 149 104 182 143 193 108 141 182]
[[151]
 [194]
 [143]
 [149]
 [114]
 [102]
 [172]
 [198]
 [138]
 [187]
 [164]
 [106]
 [139]
 [119]
 [196]
 [110]
 [119]
 [100]
 [158]
 [109]
 [109]
 [135]
 [179]
 [176]
 [150]
 [141]
 [148]
 [180]
 [123]
 [145]
 [128]
 [157]
 [140]
 [154]
 [190]
 [101]
 [146]
 [116]
 [129]
 [197]
 [167]
 [151]
 [187]
 [137]
 [188]
 [144]
 [176]
 [164]
 [156]
 [101]
 [147]
 [182]
 [148]
 [146]
 [167]
 [112]
 [149]
 [104]
 [182]
 [143]
 [193]
 [108]
 [141]
 [182]]
[[151 194]
 [143 149]
 [114 102]
 [172 198]
 [138 187]
 [164 106]
 [139 119]
 [196 110]
 [119 100]
 [158 109]
 [109 135]
 [179 176]
 [150 141]
 [148 180]
 [123 145]
 [128 157]
 [140 154]
 [190 101]
 [146 116]
 [129 197]
 [167 151]
 [187 137]
 [188 144]
 [176 164]
 [156 101]
 [147 182]
 [14

In [22]:
# 4. Create an array of (5,5) in which all the values will be 7.
arr = np.full((5,5),7)
arr

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [33]:
# 5. difference b/w view vs copy with example.
'''
view create a new array object that refers to the same data as the original array.
changes in the new array will affect original array.
created through simply assigning it to orginal array.

copy creates a new independent array object in a seperate memory location.
changes to the copy doesnt affect original array.
created through copy() function.
'''
arr = [1,2,3,5]
view_arr = arr
view_arr[0] = 4
print(view_arr)
print(arr)

arr = [1,2,3,5]
copy_arr = arr.copy()
copy_arr[0] = 4
print(copy_arr)
print(arr)

[4, 2, 3, 5]
[4, 2, 3, 5]
[4, 2, 3, 5]
[1, 2, 3, 5]


In [34]:
# 6. difference b/w linspace() and unique() with code of example
'''
numpy.linspace() generates an array of a specified number of evenly spaced values over a given interval
and numpy.unique() finds the unique elements of an array. It returns the sorted unique elements array.
'''
lin = np.linspace(1,10,5)
print(lin)

uni = np.unique([1,1,2,2,3,3,4,4,5,5])
print(uni)

[ 1.    3.25  5.5   7.75 10.  ]
[1 2 3 4 5]


In [35]:
# 7. what is hstack() and vstack()? Create 4 array and connect it via hstack, vstack
'''
hstack combines the arrays horizontally i.e rowwise
vstack combines the arrays vertically i.e columnwise
'''
arr1 = np.array([1,2])
arr2 = np.array([3,4])
arr3 = np.array([5,6])
arr4 = np.array([7,8])
hst = np.hstack((arr1,arr2,arr3,arr4))
print(hst)
vst = np.vstack((arr1,arr2,arr3,arr4))
print(vst)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [50]:
# 8. Create an array in range 11-26. Now you have to reshape it 4*4 and
#    then you have to calculate total sum, row wise sum and column wise sum.
arr = np.arange(11, 27)
print(arr)
rearr = arr.reshape((4,4))
print(rearr)

print('total Sum :- ', rearr.sum())
print('rowwise sum :-' ,rearr.sum(axis=1))
print('columnwise sum', rearr.sum(axis=0))

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]]
total Sum :-  296
rowwise sum :- [50 66 82 98]
columnwise sum [68 72 76 80]
