In [1]:
# Introduction to numpy
'''
Numpy is an open-source library that is used to handle
scientific calculations.
'''

'\nNumpy is an open-source library that is used to handle \nscientific calculations. \n'

In [2]:
# Difference b/w list and numpy:-
'''
1. List is Hetrogenous data type and numpy is homogeneous data type.
2. List takes more memory as compare to numpy.
3. List takes more execution time as  compare to numpy.
4. Numpy is faster than list.
'''

'\n1. List is Hetrogenous data type and numpy is homogeneous data type.\n2. List takes more memory as compare to numpy.\n3. List takes more execution time as  compare to numpy.\n4. Numpy is faster than list.\n'

In [3]:
import numpy as np


In [4]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Matrix --- > rows, columns
# total Eelemnts = row * column = 3*3 = 9

In [7]:
print('Total Rows and columns :', b.shape)
print('Total Elements :', b.size)

Total Rows and columns : (3, 3)
Total Elements : 9


In [8]:
a = [[1,2,3,1],[4,5,6,2],[7,8,9,3]]
b = np.array(a)
print('Total Rows and columns :', b.shape)
print('Total Elements :', b.size)

Total Rows and columns : (3, 4)
Total Elements : 12


In [9]:
# how to check dimension of a matrix ?
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a.ndim

2

In [11]:
##### Why learning numpy

# Images ---> Pixels(0-255) ----> Normalize(0-1) ---> Matrix ----> operations
# DL ----> Artificial Nueron ---> weight ----> randomly creations ----> Numpy
# Datasets ----> Dummy entry ----> random module ---> attach pandas

In [12]:
# Pre-defined Functions in Numpy

In [13]:
# (1). zeros() ----> It will create an array in which all the values will be zero
# 1-d and multi-dimensional both

In [14]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [15]:
a = np.zeros((3,4))

In [16]:
a.shape

(3, 4)

In [17]:
# (2). ones() ---> It will create an array in which all the values will be 1
# 1-d or multi-dimensional both

In [18]:
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [19]:
a.shape

(4,)

In [20]:
a = np.ones((4,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
a.shape

(4, 5)

In [22]:
'''
3). eye() :- It will create an array in which
diagonal positional element will be set to 1 and rest all are 0.
'''

a = np.eye(3) ### rpws = columns ----> Symmentric metrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
a = np.eye(3,4) ### rows != columns ---> Assymetric metrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [24]:
'''
4). diag() ---> It will create an array in which we can set our custom
values at diagonal position.
'''
a = np.diag([1,43,67,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 43,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 90]])

In [25]:
'''
5). Random module --->
a). Randint() ---> It will create an array randomly in a given range.
syntax : np.random.randint(min_range, max_range, total_numbers)
'''
a= np.random.randint(1,10,3)
a

array([4, 8, 8])

In [26]:
'''
b). rand() ---> It will generate random numbers from 0-1.
syntax : np.random.rand(total_random_numbers)
'''
a= np.random.rand(4)
a

array([0.07310991, 0.64486393, 0.18810457, 0.07391491])

In [27]:
'''
c). dataset(emp_data)(emp-id,salary, domain) ---> randomly column add(working_hours)
c). seed() ----> It will fix or lock our generated data.
syntax :
np.random.seed(45)
a= np.random.randint(1,10,2)
'''
np.random.seed(34)
a = np.random.randint(1,10,3)
a


array([2, 7, 6])

In [28]:
####   View Vs Copy  ####

In [29]:
a = np.array([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [30]:
b = a[1:4]
b[:]=0
a

array([10,  0,  0,  0, 50, 60, 70, 80])

In [31]:
# copy
a = np.array([10,20,30,40,50,60,70,80])
b = a[1:4].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [32]:
# Reshaping the array
# total rows * columns = total_elements

In [33]:
a = np.random.randint(1,50,12)
a

array([ 5, 36,  6, 12, 43, 15, 30, 19, 30, 26, 30, 39])

In [34]:
# 1*12, 12*1
# 2*6,  6*2
# 3*4,  4*3

In [35]:
a.reshape(2,6)

array([[ 5, 36,  6, 12, 43, 15],
       [30, 19, 30, 26, 30, 39]])

In [36]:
a.reshape(3,4)

array([[ 5, 36,  6, 12],
       [43, 15, 30, 19],
       [30, 26, 30, 39]])

In [37]:
# a.reshape(6,3)  ---> Error

In [38]:
# y = mx+b
# m = matrix -----> weights
# x = values ----> matrix

# matrix(columns) * (row)matrix

In [39]:
a.shape

(12,)

In [40]:
a.reshape(2,-1)

array([[ 5, 36,  6, 12, 43, 15],
       [30, 19, 30, 26, 30, 39]])

In [41]:
a.reshape(-1,3)

array([[ 5, 36,  6],
       [12, 43, 15],
       [30, 19, 30],
       [26, 30, 39]])

In [42]:
# Operations on Array
a = np.arange(1,5,2)
a

array([1, 3])

In [43]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [44]:
a*2

array([2, 4, 6, 8])

In [45]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [46]:
a+b

array([ 6,  8, 10, 12])

In [47]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [48]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [49]:
a+b

array([[ 6,  8],
       [10, 12]])

In [50]:
a-b

array([[-4, -4],
       [-4, -4]])

In [51]:
a*b  ### this is for matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [52]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [53]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [55]:
b = a>10
a[b]

array([11, 12, 13, 14])

In [56]:
a = np.arange(1,4)
a**2

array([1, 4, 9])

In [57]:
a**3

array([ 1,  8, 27])

In [58]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
np.sum(a)

np.int64(45)

In [60]:
np.sum(a, axis =1)  ### axis = 1 means row wise operation

array([ 6, 15, 24])

In [61]:
np.sum(a, axis=0)   ### axis = 0 means column wise operation

array([12, 15, 18])

In [63]:
# Unique()
'''
It will create an array in which it will remove duplicate values and
it will return 3 arrays:
arr ---> Unique elements of array
return_index = True -----> Indexing od unique element
return_counts = True -----> Frequency of each unique element.
'''

a = np.array([1,2,3,1,1,1,1,4,5,4,4,4,4,6,7])
a

array([1, 2, 3, 1, 1, 1, 1, 4, 5, 4, 4, 4, 4, 6, 7])

In [64]:
b = np.unique(a, return_index =True, return_counts = True)
b

(array([1, 2, 3, 4, 5, 6, 7]),
 array([ 0,  1,  2,  7,  8, 13, 14]),
 array([5, 1, 1, 5, 1, 1, 1]))

In [66]:
# linspace()
'''
It will return an array in which elements
will be same gap in a given range.
syntax:
np.linspace(min, max, stepup_totalnumbers)
'''
a = np.linspace(1, 10, 5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [69]:
# Horizontal and Vertical Stacking
'''
hstack :- It will add 2 or more arrays in horizontally
vstack :- It will add 2 or more arrays in verically
'''

a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [71]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [72]:
c = np.arange(9,13)
c

array([ 9, 10, 11, 12])

In [73]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [74]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])